feat: moved sso scripts and added mfa scripts

diff --git a/zsh/.zfunc/aws-login b/zsh/.zfunc/aws-login
--- a/zsh/.zfunc/aws-login
+++ b/zsh/.zfunc/aws-login
@@ -1,34 +1,34 @@
-# Requires JQ and awscli, brew install jq awscli
+#!/usr/bin/env bash
+# Requires JQ and the AWS CLI
 
-if [ -z "${1}" ]; then
-  echo "Usage: aws-login AWS_PROFILE" 1>&2
+if [[ -z "${1}" || -z "${2}" ]]; then
+  echo "Usage: aws-login AWS_PROFILE MFA_CODE"
   return
 fi
 
-if ! command -V jq > /dev/null; then
-  echo "The jq command is required for this function to work."
+if ! command -v jq &> /dev/null; then
+  echo "Error: This script requires that you install 'jq'"
   return
 fi
 
-SSO_START_URL=$(aws configure get "profile.${1}.sso_start_url")
+ROLE_ARN=$(aws configure get "profile.${1}.role_arn")
+SERIAL_ARN=$(aws configure get profile.${1}.mfa_serial)
+SESSION_NAME="${SERIAL_ARN##*/}"
 
-if [ -z "${SSO_START_URL}" ]; then
-  echo "profile (${1}) not configured for sso; Missing sso_start_url" 1>&2
+# Validate these variables actually have values
+if [[ -z "${ROLE_ARN}" || -z "${SERIAL_ARN}" ]];then
+  echo "Error: Please choose a valid profile. It must contain 'role_arn' and 'mfa_serial'"
   return
 fi
 
-ACCESS_TOKEN=$(cat ~/.aws/sso/cache/*.json | jq -r --arg url "${SSO_START_URL}" 'select(.startUrl==$url).accessToken')
-SSO_ACCOUNT_ID=$(aws configure get "profile.${1}.sso_account_id")
-SSO_ROLE_NAME=$(aws configure get "profile.${1}.sso_role_name")
-CREDS=$(aws sso get-role-credentials --account-id "${SSO_ACCOUNT_ID}" --role-name "${SSO_ROLE_NAME}" --access-token "${ACCESS_TOKEN}" --profile "${1}" 2>/dev/null)
+JSON=$(aws sts assume-role --role-arn ${ROLE_ARN} --role-session-name ${SESSION_NAME} --serial-number ${SERIAL_ARN} --token-code ${2})
 
-if [ "$?" != "0" ]; then
-  aws sso login --profile "${1}"
-  ACCESS_TOKEN=$(cat ~/.aws/sso/cache/*.json | jq -r --arg url "${SSO_START_URL}" 'select(.startUrl==$url).accessToken')
-  CREDS=$(aws sso get-role-credentials --account-id "${SSO_ACCOUNT_ID}" --role-name "${SSO_ROLE_NAME}" --access-token "${ACCESS_TOKEN}" --profile "${1}")
+if [ $? -eq 0 ]; then
+  export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' <<< "${JSON}")
+  export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' <<< "${JSON}")
+  export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' <<< "${JSON}")
+  export AWS_PROFILE="${1}"
+else
+  echo "Error: Unable to get temporary credentials for role ${ROLE_ARN}"
 fi
 
-export AWS_ACCESS_KEY_ID=$(jq -r '.roleCredentials.accessKeyId' <<< "${CREDS}")
-export AWS_SECRET_ACCESS_KEY=$(jq -r '.roleCredentials.secretAccessKey' <<< "${CREDS}")
-export AWS_SESSION_TOKEN=$(jq -r '.roleCredentials.sessionToken' <<< "${CREDS}")
-export AWS_PROFILE="${1}"
